---

- name: Ensure GPG is installed
  ansible.builtin.apt:
    name: gpg-agent
    state: present

- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    mode: '0755'
    state: directory

- name: Download GitHub CLI GPG key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'

- name: Add GitHub CLI APT repository using deb822_repository
  ansible.builtin.deb822_repository:
    name: github-cli
    types: [deb]
    uris: https://cli.github.com/packages
    suites: stable
    components: [main]
    architectures: [amd64]
    signed_by: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    enabled: true
    state: present
