---

# Install prerequisites
- name: Add the GitHub cli tool repository
  import_tasks: ./add-github-cli-repo.yml

- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: present
  loop:
    - gh
    - jq
    - uncrustify

# Install hdev
- name: Install hdev
  import_tasks: ./install_hdev.yml

# Add Constants values
- name: Populate Constants files
  copy:
    content: "{{ constant.value }}"
    dest: "/opt/hdev/cli/constants/{{ constant.key }}"
    mode: "0644"
  loop_control:
    loop_var: constant
  with_dict: "{{ hdev_default_constants | combine(hdev_constants | default({}), recursive=True) }}"


# Populate CMDB with the Servers
- name: Populate the cmdb with the servers in the cluster
  include_tasks: create-cmdb.yml
  vars:
    hostname: "{{ hdev_cluster_node.key }}"
    devices: "{{ hdev_cluster_node.value }}"
  loop_control:
    loop_var: hdev_cluster_node
  loop: "{{ hdev_servers | dict2items }}"


# Set current node
- name: Check which devices are available on current node
  stat:
    path: "/opt/hdev/cli/cmdb/{{ inventory_hostname }}/devices_{{ device_type }}"
  register: node_devices
  loop_control:
    loop_var: device_type
  loop:
    - network
    - acap_fpga
    - gpu

- name: Create symlink to device files of current node to root of hdev
  file:
    src: "/opt/hdev/cli/cmdb/{{ inventory_hostname }}/devices_{{ device_type }}"
    dest: "/opt/hdev/cli/devices_{{ device_type }}"
    owner: root
    group: root
    state: link
    force: true
  loop_control:
    loop_var: device_type
  loop:
    - network
    - acap_fpga
    - gpu
  when: >
    (
      node_devices.results
      | selectattr('device_type', 'equalto', device_type)
      | first
    ).stat.exists | default(false)
